import './components/validate-form/validate-form'
import './components/ajax-form/ajax-form'
import './components/ajax-html/ajax-html'
import './components/dropdown/dropdown'
import './components/exclusive-checkbox/exclusive-checkbox'
import './components/select-all/select-all'
import './components/tabs/tabs'
import './components/until-selected/until-selected'
import './components/search-filter/search-filter'
import { apply, isSupported } from 'invokers-polyfill/fn'
if (!isSupported()) apply()
