import './components/validate-form'
import './components/ajax-form'
import './components/ajax-html'
import './components/dropdown'
import './components/exclusive-checkbox'
import './components/select-all'
import './components/until-selected'
import './components/search-filter'
import { apply, isSupported } from 'invokers-polyfill/fn'
if (!isSupported()) apply()
